version: '2'

services:
  dnsdock:
    image: aacebedo/dnsdock:latest-amd64
    container_name: dnsdock
    restart: always
    ports:
      - "172.17.0.1:53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
