version: '2'

services:
  agent:
    image: whilp/ssh-agent
    volumes:
      - data:/ssh

  key:
    image: whilp/ssh-agent
    command: 'ssh-add $HOME/.ssh/id_rsa$SSH_KEY_PREFIX'
    volumes:
      - data:/ssh
      - '$HOME/.ssh:$HOME/.ssh:ro'
    depends_on:
      - agent

volumes:
  data:
    driver: local
